- name: variables
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: Please enter course name
    private: false # it is not confidential information
  - name: DURATION 
    prompt: PLease enter Duration
  - name: TRAINER
    prompt: Please enter the trainer name
  tasks:
  - name: print couse information
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"